### ISSUE TITLE
I get nothing when "Find Reference"

### ISSUE THREAD

**Issue by zhangshengping** [pnedev/nppgtags#1]
I use nppgtags to browser c source code. I have created gtags file in the root direction, but when I the try to "Find Refernece" of a symbol, I got nothing. Here is the screenshot.
![](https://drive.google.com/uc?export=view&id=0Bz3OUm_DrURoVUI5MU5GZlZlMU0)

**Comment by pnedev** [comment]
The references are kept in the GRTAGS file in your project folder. Try re-creating your database with the default parser (if you haven't touched that in your NppGtags settings it should already be set).

The symbol you are searching looks like a part of composite define and it is quite possible that the parser has failed finding it. The solution in this case is to use "Search In Source Files" command - it will simply grep your project's source files for the symbol and find all it's uses in the code.

**Comment by zhangshengping** [comment]
Thank you for your suggestion. It works.
