### ISSUE TITLE
[Question] Update database outside of NppGtags

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [pnedev/nppgtags#10]
It's possible to manually update database by using `cmd` and get the same result as NppGtags generate (ctags parser)?
Let say I have that folders and files:
`D:\Notepad++\plugins\NppGTags\` << here sits all bin/dll/conf files
`D:\project\` << root of my code where all database files exist.
Now I want run in cmd bin file from `Notepad++` and update database in `project`. But I don't know what bin file should invoke and how to indicate the source and output as argument.
I don't want update database from  NppGtags options because before that action I have to do some other actions and I would prefer to automate all of them.

**Comment by pnedev** [comment]
It is possible to manually re-create the database:

`cd D:\project\`
`D:\Notepad++\plugins\NppGTags\gtags.exe  -c --skip-unreadable  --gtagsconf "D:\Notepad++\plugins\NppGTags\gtags.conf" --gtagslabel=%Parser`

where %Parser is `default` (for GTags native parser), `ctags` or `pygments`.

It will generate the whole database again.
The plugin updates the database by changed file (only the changed file gets re-indexed - considerably reduces database update).
If you like to do so you'll need also the option ` --single-update "%relative file path"` added on the above command line.

**Comment by ArkadiuszMichalski** [comment]
Thx, works perfect with Node.js.
