### ISSUE TITLE
support add character as part of word

### ISSUE THREAD

**Issue by linpengcheng** [pnedev/nppgtags#12]
support add character as part of Word.
example: add Lisp (clojure) word character  list
!$%*-+><.?/

**Comment by pnedev** [comment]
Can you be more specific?
I didn't understand your suggestion nor what the problem is.

**Comment by pnedev** [comment]
@linpengcheng , any update?

**Comment by linpengcheng** [comment]
Sorry, the last time I was wrong with my configuration, type "a", auto-complete can only display "app",
Today, The configuration is correct, enter "a", auto-complete can fully display the list "app, about-page, app-routes".
