### ISSUE TITLE
Add more settings and functions to the search result window

### ISSUE THREAD

**Issue by pidgeon777** [pnedev/nppgtags#15]
Actually when searching for a reference, the results are always shown in a collapsed tree. Please add a setting to change this behavior.
For example, in many cases it would be better to always show the search result tree already expanded.

Two customizable shortcuts for expanding/collapsing the search results tree would also be nice.

**Comment by pnedev** [comment]
Please look at this issue:
https://github.com/pnedev/nppgtags/issues/8

Thanks.
