### ISSUE TITLE
database can be automatically deleted, don't display warning messages

### ISSUE THREAD

**Issue by linpengcheng** [pnedev/nppgtags#18]
1. The current database can be automatically deleted When exiting notepad++,  just like NppCCompletionPlugin.

2. It can be set to don't display warning messages of nppgtags.

**Comment by pidgeon777** [comment]
> The current database can be automatically deleted When exiting notepad++, just like NppCCompletionPlugin.

NppCCompletionPlugin creates a ctags.tmp file which optionally can be automatically deleted following the closure of Notepad++. This is useful in order to keep everything clean.

Automatic cleanup of NppGTags generated files could be useful indeed, I think this is what @linpengcheng meant. I agree with him, didn't think of this at first.

**Comment by pnedev** [comment]
Thanks for clarifying, that's what I thought too.

I don't like this behavior for 2 reasons:

1) The database config will be gone with the database deletion and the user will need to re-config it on every Notepad++ restart.
2) I personally work with very large code bases and database creation takes noticeable time. I don't want to re-create the database on every Notepad++ restart and wait the process to finish before I can start to work.

**Comment by pidgeon777** [comment]
I think that @linpengcheng meant to add an option to automatically delete or not the following files created by NppGTags:

```
GPATH
GRTAGS
GTAGS
NppGTags.cfg
```

This is how NppCCompletionPlugin actually works.

With some smaller projects (probably the vast majority of cases) it could be useful, I think. Eventually, a user could decide between enabling this option or not, as it already happens with NppCCompletionPlugin.

**Comment by pnedev** [comment]
That might be useful for smaller projects indeed but loosing the database config is not good thing anyway.
It is user configuration that needs to be preserved.

**Comment by linpengcheng** [comment]
I also think that needs to be preserved (NppGTags.cfg),
but I hope that the tag files can choose whether to delete automatically.

I added a .ctags file in the database directory for custom Clojure language, every time I auto-update (or create) database, there will be a message:
ctags: Warning: Language "Clojure" already defined.

**Comment by pnedev** [comment]
@linpengcheng ,

Could you upload your `.ctags` file so I can investigate the issue?

**Comment by linpengcheng** [comment]
--langdef=Clojure
--langmap=Clojure:.clj.cljs.cljc.cljr.cljx
--regex-clojure=/\([ \t]*create-ns[ \t]+([-[:alnum:]*+!_:\/.?]+)/\1/n,namespace/
--regex-clojure=/\([ \t]*def[ \t]+([-[:alnum:]*+!_:\/.?]+)/\1/d,definition/
--regex-clojure=/\([ \t]*defn[ \t]+([-[:alnum:]*+!_:\/.?]+)/\1/f,function/
--regex-clojure=/\([ \t]*defn-[ \t]+([-[:alnum:]*+!_:\/.?]+)/\1/p,private function/
--regex-clojure=/\([ \t]*defmacro[ \t]+([-[:alnum:]*+!_:\/.?]+)/\1/m,macro/
--regex-clojure=/\([ \t]*definline[ \t]+([-[:alnum:]*+!_:\/.?]+)/\1/i,inline/
--regex-clojure=/\([ \t]*defmulti[ \t]+([-[:alnum:]*+!_:\/.?]+)/\1/a,multimethod definition/
--regex-clojure=/\([ \t]*defmethod[ \t]+([-[:alnum:]*+!_:\/.?]+)/\1/b,multimethod instance/
--regex-clojure=/\([ \t]*defonce[ \t]+([-[:alnum:]*+!_:\/.?]+)/\1/c,definition (once)/
--regex-clojure=/\([ \t]*defstruct[ \t]+([-[:alnum:]*+!_:\/.?]+)/\1/s,struct/
--regex-clojure=/\([ \t]*defrecord[ \t]+([-[:alnum:]*+!_:\/.?]+)/\1/s,struct/
--regex-clojure=/\([ \t]*intern[ \t]+([-[:alnum:]*+!_:\/.?]+)/\1/v,intern/
--regex-clojure=/\([ \t]*ns[ \t]+([-[:alnum:]*+!_:\/.?]+)/\1/n,namespace/
--exclude=target
--exclude=out
--exclude=.git

**Comment by linpengcheng** [comment]
@pnedev 
Your plugin is very helpful to me, thank you.
