### ISSUE TITLE
Improve automation of database creation

### ISSUE THREAD

**Issue by pidgeon777** [pnedev/nppgtags#19]
Actually, this is the popup shown when the database is missing:

![image](https://user-images.githubusercontent.com/13739892/50855143-53dcc200-1387-11e9-9b9f-dcf4a103ccf5.png)

Maybe it would be cool to add a database creation option to the popup? For example:

Title : Gtags database not found. Do you want to create it?
Answers: Yes | No

This would appear everytime a user is trying to do some actions which would involve the existence of a database. Just a little idea.

**Comment by pnedev** [comment]
Good idea, here is a test x86 binary:
https://ci.appveyor.com/api/buildjobs/0ar9p6y0ku87xf6u/artifacts/NppGTags.x86.Release.v140_xp.dll

The user command that triggered the database creation in that case is not continued after the creation - it is simply ignored. The user has to redo it.

**Comment by pnedev** [comment]
> Your last sentence, however, is quite unclear to me ...

OK, if the database does not exist and you start _Find Definition_ for the tag `foo` for example the new popup appears and asks you if you want to create a database. You say yes and the database is created BUT the _Find Definition_ command you started is NOT continued - it is aborted. You'll have to start it again.

**Comment by pidgeon777** [comment]
Ok, everything is clear now. Thanks!
