### ISSUE TITLE
ctags' extend is not supoort in windows

### ISSUE THREAD

**Issue by lantianjialiang** [pnedev/nppgtags#25]
I extend ctags to support our DSL.

> \# pattern list
> --langdef=t2k_plist
> --map-t2k_plist=+.plist
> --kinddef-t2k_plist=g,Pattern,Pattern
> --regex-t2k_plist=/^Pattern[ \t]*([a-zA-Z0-9_]+)/\1/g/ 

and save those content to ctags config file.
when I run ctags from command line, it works.

but when I run npptags from notepad++(change setting to ctags), it's not work.

could you please check it?

thanks.

**Comment by pnedev** [comment]
@lantianjialiang ,

Where do you do these settings (what is the ctags config file)?

Which ctags.exe are you using? The one from NppGTags plugin folder or your own ctags.exe?

If you haven't tried that already try putting your ctags settings file in the NppGTags plugin folder (where NppGTags ctags.exe is located -> NppGTags.dll folder/NppGTags

BR

**Comment by pnedev** [comment]
No response so I'm closing this issue.

**Comment by lantianjialiang** [comment]
> 
> 
> @lantianjialiang ,
> 
> Where do you do these settings (what is the ctags config file)?
I put it into C:\Users\$user\ctags.d
> 
> Which ctags.exe are you using? The one from NppGTags plugin folder or your own ctags.exe?
I replace ctags.exe under NppGTags plugin with Exuberant Ctags. It's worked.
C:\Program Files (x86)\Notepad++\plugins\NppTags>ctags.exe --help
Universal Ctags 0.0.0(ff180005), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jul 18 2019, 00:10:09
  URL: https://ctags.io/
> 
> If you haven't tried that already try putting your ctags settings file in the NppGTags plugin folder (where NppGTags ctags.exe is located -> NppGTags.dll folder/NppGTags
> 
> BR

Sorry for long time no response. we can't access github sometimes in our country.

**Comment by pnedev** [comment]
I don't know where your _ctags.exe_ looks for its config file but as I said, try putting _ctags.d_ where the _ctags.exe_ is located.
