### ISSUE TITLE
NppGTags not works in windows 10

### ISSUE THREAD

**Issue by xiehao5** [pnedev/nppgtags#26]
The NppGTags not works in windows 10 64-bit, however the same environment (NPP 7.7.1 64-bit and NppGTags 4.4.2) works well in Win 7.

Could you add windows 10 support?
Thanks.

**Comment by pnedev** [comment]
I do not have Win10 setup on my side.
Could you briefly describe what exactly happens, how doesn't it work?

BR

**Comment by xiehao5** [comment]
That is odd. I reinstall the plugin and it works well now.

**Comment by gurikbal** [comment]
> The NppGTags not works in windows 10 64-bit, however the same environment (NPP 7.7.1 64-bit and NppGTags 4.4.2) works well in Win 7.
> 
> Could you add windows 10 support?
> Thanks.

occur was both in x86 and x64 dll using win 10 x64 . NppGTags 4.4.2 works fine after install [Visual C++ redistributable 2015-2019](https://support.microsoft.com/en-sg/help/2977003/the-latest-supported-visual-c-downloads)

and now NppGTags updated to 4.4.3 

![_001](https://user-images.githubusercontent.com/36083297/68304314-83ee1200-00cb-11ea-8902-c9de95946b94.gif)
