### ISSUE TITLE
Place & search all DLLs  etc. directly in the new plugin dir, not under another "NppGTags"

### ISSUE THREAD

**Issue by lunakid** [pnedev/nppgtags#27]
![image](https://user-images.githubusercontent.com/698307/62488051-aa966700-b7c3-11e9-819e-9d834cbd68b4.png)

AFAIU, the dir layout changed in NP++, but the plugin could hopefully easily support both the old and the new one. (Actually, it should prefer the new one.)

I mean, of course, it works fine now, but as my grandfather would have said, had he not died in WWII: "Never trust a program that uses a duplicated "Name/Name" path!" ;)

**Comment by pnedev** [comment]
Hi @lunakid ,

What's the reason to move the library binaries to the same folder?
I prefer them to be in separate one as they might be changed separately from the plugin dll.

BR

**Comment by lunakid** [comment]
Oh, it's perfectly fine to keep them separated then. It's just the generic issue of lost semantics with duplicated subdir names that bothers me (and since I'm nobody special, possibly others, too, then).

According to my limited understanding, you need to support a dual layout, one with a single subdir (for the old NP++), another with the extra level (for the new). If that's the case, I assumed there's not much you can do about the dir _names_ themselves. But if you _allowed_ loading the extra DLLs from the same dir where `NppGTags.dll` is, then at least a manual install could avoid that duplicate subdir with the same name as its parent -- which now seems impossible (for failing to load the extraDLLs from the same dir as `NppGTags.dll`).

Of course, all this assuming no compelling reasons against it. And, anyway, it's just my quiet holy war for semantic purity in filesystem object naming, and to let my imaginary grandpa rest in peace. :)

Cheers, and thank you very much for your nice plugin! (y)

_(BTW, an aside: just forked NP++ yesterday for some tinkering, and udpated it (locally, not pushed yet) to C++17 compliance, plus got rid of the ancient, leftover MFC/ATL dependencies (CString, CComCriticalSection etc.), so it now finally also builds on a fresh & bare-bones VC 2019 Community Ed. (Upstream has some deprecated C++ std stuff, requiring an older compiler, and also either a "PRO" VS edition, or extra SDKs for MFC/ATL). If I find myself maintaining the fork for any longer term, I'd love to hear what a plugin developer like you would prefer to have differently in NP++! So if you feel like, and has anything to say, I'm all ears. Either in the [Issues](https://github.com/lunakid/notepad-plusplus-gilded/issues), or in any channel you may see fit. Thanks!)_

**Comment by pnedev** [comment]
The plugin looks for its external binaries in _NppGTags_ subfolder relative to its dll path.
As you certainly know all plugins' dlls before were located in one folder and I needed a distinct subfolder there for the external binaries that wouldn't mess with another plugin.
There is no need to change anything - just place _NppGTags.dll_ and the external binaries folder wherever the specific Notepad++ version requires them to be.

> BTW, an aside: just forked NP++ yesterday ...

OK, great, I'll have that in mind, thanks :)

**Comment by lunakid** [comment]
> The plugin looks for its external binaries in _NppGTags_ subfolder relative to its dll path.

Yes, and my gripe is that it *only* looks there. I'd prefer it to *also* fall back to `dirname(NppGTags.dll)`.

> As you certainly know all plugins' dlls before were located in one folder and I needed a distinct subfolder there for the external binaries that wouldn't mess with another plugin.

Yes, and adding a subdir is a very welcome change, of course.

> There is no need to change anything - just place _NppGTags.dll_ and the external binaries folder wherever the specific Notepad++ version requires them to be.

Well, that's not exactly true, hence this issue here.

1. The optimal layout, I'd prefer:

```
    plugins/
        NppGTags/  <- your "canonical" plugin dir name, also as NP++ installs it. I do *not* want to change that.
            NppGTags.dll
            subdir-for-your-ext-stuff/  <- with any name, *except* for NppGTags
                ...extra DLLs etc.
```      
2. Or this (at least with a manual install), assuming (1) is unlikely to happen:

```
    plugins/
        NppGTags/  <- your "canonical" plugin dir name, also as NP++ installs it. I do *not* want to change that.
            NppGTags.dll
            ...extra DLLs etc.
```
Currently, both of these are impossible:

a) If I just let NP++ install it, we get:

```
    plugins/
        NppGTags/
            NppGTags.dll
            NppGTags/
                ...extra dlls etc.
```
b) And, it I try (2) manually, we get the error I copied.

**Comment by pnedev** [comment]
Hi,

Sorry for the late reply I had several days off.

Well, I understand but I like it that way. I prefer to keep the folder name the same as the DLL because of possible future changes in Notepad++. It doesn't hurt anyway.
Having the external binaries in the same folder as the main DLL is a mess and I don't like it.

Thanks for the suggestion anyway and keep up the good work on your Notepad++ clone - it could definitely use some improvements.

BR
