### ISSUE TITLE
Support for excluding certain sub paths from tag generation.

### ISSUE THREAD

**Issue by quantumman42** [pnedev/nppgtags#30]
To improve tagging speed it would be nice if there was a way to exclude sub paths from tag generation instead of just search results. Not sure if this is something that can be accomplished in nppgtags or requires changes in Universal CTags

As a bit of justification, a project I work on takes about 45min to tag (and generates a ~2GB tag file) being able to exclude chunks of the source tree I don't care about would speed up tagging significantly.

**Comment by pnedev** [comment]
@quantumman42 ,

Yes, I'd like to have that too for the same reasons but it is not something I can do from NppGTags plugin directly as it is just a front-end. A change in the database parser itself is needed and it is external software I'm just using.

I actually posted a feature request about that 3 or 4 years ago to the Global Tags developer and he considered it a good thing to have (database creation folder exclusion) but it is not implemented yet.
I hope it will be done someday.

**Comment by quantumman42** [comment]
That makes sense.
