### ISSUE TITLE
Auto expand all folds

### ISSUE THREAD

**Issue by vinsworldcom** [pnedev/nppgtags#32]
A nice option would be to have auto-expand all folded code in the pop-up window automatically after a new lookup.

**Comment by pnedev** [comment]
Hi @vinsworldcom ,

You can expand all results if you double click with the mouse the very first line or click its margin part once or simply press 'ALT +' key combination. 'ALT -' colapses all results.

If you mean to auto expand previously expanded items in the same lookup (re-lookup) then it would be useful indeed but I don't have time to work on the plugin.

Thanks for the suggestion anyway.
