### ISSUE TITLE
Python 3 and pygments-parser.py

### ISSUE THREAD

**Issue by HongThatCong** [pnedev/nppgtags#33]
On Python 3, the pipe between pygments-parser.dll and pygments-parser.py will not work.
Because the dll create Ansi Pipe, pygments-parser.py uses stdin.readline(), but on Python3, stdin.readline() read Unicode chars.
Please test them.
Thanks.

**Comment by pnedev** [comment]
`pygments-parser.dll` and `pygments-parser.py` are both part of Global GTags which I am directly using and I don't plan to update them, sorry. The plugin is simply a front-end that presents the GTags query results in a more convenient manner in Notepad++.
I am not sure the GTags parser actually parses Unicode files properly.

**Comment by HongThatCong** [comment]
What version of Python you are using ?
Did you test pygments-parser.py with Python 3

**Comment by pnedev** [comment]
I actually don't use Pygments myself.
Tested it long time ago with Python 2.

**Comment by HongThatCong** [comment]
Thanks @pnedev 
It run OK with Python 3.
