### ISSUE TITLE
Occur "vector<T> too long" with Notepad++ 8.4 and later

### ISSUE THREAD

**Issue by JimmyHwang** [pnedev/nppgtags#35]
I got "vector<T> too long" warning dialog on Npp 8.4 and later when I use "Find definition" of NppGTags, but 8.3.3 is work fine, Wish who can help fix that, this is good plugin for me.

![image](https://user-images.githubusercontent.com/38301/176435902-1d10f83f-4146-4f99-b42b-26ac0ed72644.png)

Notepad++ v8.4.2 (32-bit)
Build time : May 29 2022 - 16:45:17
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : “\MXUSER4\www\StockCafe\Workplace.npp”
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 21H2
OS Build : 19044.1766
Current ANSI codepage : 950
Plugins :
NppGTags (4.5)

**Comment by pnedev** [comment]
NppGTags 4.5.0 is not compatible with Notepad++ versions above 8.3.3 due to internal Scintilla component changes in Notepad++.

Download NppGTags 5.0.0 and install it manually for Notepad++ 8.4, 8.4.1 or 8.4.2 as described in https://github.com/pnedev/nppgtags/issues/34#issuecomment-1165657997
