### ISSUE TITLE
library lookup works only when it is on the same partiton as project

### ISSUE THREAD

**Issue by panqjhust163** [pnedev/nppgtags#36]
Notepad++ 8.4.3
nppgtags     5.0.0

library database was setting over, but will not find tags in library database.
once version, maybe NPP 8.1 and ng 4.4, this function is ok.
NppGTags.cfg seems ok, after adding library path

**Comment by pnedev** [comment]
I didn't get what the problem is.
I just tested NppGTags 5.0.0 with Notepad++ 8.4.2 and it is working as expected.
Is it working OK for you with those versions ?

**Comment by panqjhust163** [comment]
In my test case, using Library database, compare to " Find Definition"
1 npp 8.1.9.2 nppgtags 4.4.3,   this function work well.
2 npp 8.4.2/8.4.3  NppGTags 5.0.0, it doesnot work.

**Comment by panqjhust163** [comment]
i found a little difference.  
NppGTags 4.4.3 Find Definition, just show it, at blow window. 
When using NppGTags 5.0.0 to find, the result will goto edit window, if ony one exists.
For c language.

**Comment by pnedev** [comment]
> In my test case, using Library database, compare to " Find Definition" 1 npp 8.1.9.2 nppgtags 4.4.3, this function work well. 2 npp 8.4.2/8.4.3 NppGTags 5.0.0, it doesnot work.

I suppose you have re-created the databases of both the library and the project.
By "it does not work" what exactly do you mean? It just doesn't find the definition you are looking for in the library database?
I checked again with my projects and it is working (those are C++ sources).

> NppGTags 4.4.3 Find Definition, just show it, at blow window.
When using NppGTags 5.0.0 to find, the result will goto edit window, if ony one exists.

This was requested by several users before and is the intended behavior in 5.0.0.

**Comment by panqjhust163** [comment]
If the finding symbol in project,  "Find Definition" work well.  If the symbol in library, "Find" doesnot work.
Then I test putting library in diffenent partition on windows disk.
when lib was in same partion, whether or not same directory, " Find" can work.
when lib was in other partion, it doesnot work.

**Comment by pnedev** [comment]
Ah yes,
I suppose if the library is on other partition it won't work because the library path is taken relative to the project path.
So both must be on the same disk partition.
This is current implementation limitation.

Does it mean that in your Npp 8.4.2/8.4.3 + NppGTags 5.0.0 test finding definition works OK when the library is on the same partition as the project ?

**Comment by panqjhust163** [comment]
Npp 8.4.2/8.4.3 + NppGTags 5.0.0 test ok, finding definition when the library is on the same partition as the project.
Dose this limitation can be wipe off  in future?

**Comment by pnedev** [comment]
I need to check if this limitation can be removed but it will take time that I currently don't have.
I can't promise anything in that regard.

**Comment by pnedev** [comment]
NppGTags v5.2.0 supports library DBs on other drives/partitions as well.

BR
