### ISSUE TITLE
How to add .pc extension to C source file indexing?

### ISSUE THREAD

**Issue by vnluc** [pnedev/nppgtags#37]
I have a C project folder. some of them have extension .pc and I want those files to be index as C source code then how can I do it?
for ctags I can use  `--langmap=C++:+.pc` option to include the file.

How can include this for NppGtags?

**Comment by pnedev** [comment]
You need to edit your _gtags.conf_ file manually and add the _.pc_ extension in every place where there is a `:langmap=C++\:` occurrence (there should be totally 3 places for each parser: `builtin-parser:\`, `universal-ctags:\` and `pygments-parser:\`).
The _gtags.conf_ file is located in `$YOUR_NOTEPAD++_INSTALL_FOLDER\plugins\NppGTags\bin\` folder (that is for plugin version 5.0.0).
