### ISSUE TITLE
Double click Search Result Does not open source file

### ISSUE THREAD

**Issue by vnluc** [pnedev/nppgtags#38]
I try to double click search result windows but it does not open the source file

From the document /guide:

```
Double-clicking, hitting Space or Enter on search result line will take you to the source location. You can also do that by left-clicking on the highlighted searched word in the result line. Your currently edited document location will be saved - use Go Back command to visit it again. You can 'undo' the Go Back action by using Go Forward command. By using the mouse or the arrow keys you can move around result lines and you can trigger new searches directly from the results window (same rules about the searched string apply).

Right clicking or hitting ESC will close the currently active search results tab.
```

When i do "Find definition"  it do show the seach result but when Double click search result it does not open the source file. 

I tested with Notepad++8.4.2 (64 bit) on Windows 10.

**Comment by pnedev** [comment]
What is your version of NppGTags plugin ?
It should be v5.0.0, I suppose you are with earlier version which is not compatible with Notepad++ 8.4 and above.

**Comment by pnedev** [comment]
You can check that issue regarding the same problem:
https://github.com/pnedev/nppgtags/issues/34

**Comment by vnluc** [comment]
Thank you very much, I checked and my NppGtags version 4.5.2, 

I updated version 5.0.0 now I working fine for me. Thanks
