### ISSUE TITLE
Results widow closes (ncorrectly) when clinging a result if mouse buttons are swapped.

### ISSUE THREAD

**Issue by sgmne** [pnedev/nppgtags#39]
A recent addition to nppGtags posting three key-up events and one mouse-up event causes the results window to always close, incorrectly, when navigating to a search result. A significant inconvenience.

The code at issue is:

`void ResultWin::releaseKeys()
{
    INPUT inputs[4] = {};
    ZeroMemory(inputs, sizeof(inputs));

    inputs[0].type = INPUT_KEYBOARD;
    inputs[0].ki.wVk = VK_SHIFT;
    inputs[0].ki.dwFlags = KEYEVENTF_KEYUP;

    inputs[1].type = INPUT_KEYBOARD;
    inputs[1].ki.wVk = VK_CONTROL;
    inputs[1].ki.dwFlags = KEYEVENTF_KEYUP;

    inputs[2].type = INPUT_KEYBOARD;
    inputs[2].ki.wVk = VK_MENU;
    inputs[2].ki.dwFlags = KEYEVENTF_KEYUP;

    inputs[3].type = INPUT_MOUSE;
    inputs[3].mi.dwFlags = MOUSEEVENTF_LEFTUP;

    SendInput(ARRAYSIZE(inputs), inputs, sizeof(INPUT));
}`

The issue is that the LEFTUP is always sent even when the actual button is the right button.

The fix (tested to work) is to set the correct event flag based on the button swapping state, like:

`    inputs[3].mi.dwFlags = GetSystemMetrics(SM_SWAPBUTTON) ? MOUSEEVENTF_RIGHTUP : MOUSEEVENTF_LEFTUP;
`

**Comment by pnedev** [comment]
Hello @sgmne ,
Thanks for the report and for pointing the root-cause.
The fix will be in the next release.
