### ISSUE TITLE
setting to disable error messages

### ISSUE THREAD

**Issue by marcelblum** [pnedev/nppgtags#40]
Feature request: ability to disable alert dialogs from parsing errors. The parsing isn't always perfect and with a large enough codebase there's sure to be lines that are either formatted exotically enough or use newer language syntax that they trip up the parser and result in errors like this:
![Untitled](https://user-images.githubusercontent.com/1031177/211467689-8f0ed3ef-9281-4c1d-b415-de7157d5bc68.png)
It would remove a huge annoyance to be able to suppress these messages!

I use this plugin often, thank you for maintaining.

**Comment by pnedev** [comment]
Just one question:
Do you get the same warning messages when you delete and then re-generate the database?

**Comment by pnedev** [comment]
Yes, I did some tests on my side too and 'felt' the problem.

I have made a quick fix for you and you could get the changed development binaries here: [Win64](https://ci.appveyor.com/api/buildjobs/60bl1mhbqf43q092/artifacts/NppGTags.x64.Release.v143.dll), [Win32](https://ci.appveyor.com/api/buildjobs/aef09j6mf2m16egv/artifacts/NppGTags.x86.Release.v143.dll).
Get the version corresponding to your Notepad++ bitness and you'll need to manually replace your NppGtags.dll with the one downloaded from here (the downloaded needs to be renamed to NppGtags.dll) in your plugin folder. The later can be easily accessed when you use the last entry in the Notepad++'s Plugins menu - Open Plugins Folder..
There you will find NppGTags sub-folder containing the dll.

Just one question - will it be OK for you to get such warning message only when creating the database for the first time and to have it suppressed in case of database auto-update (this includes the case when you do 'Save all' in Notepad++) ?

**Comment by marcelblum** [comment]
Awesome thanks so much! No more more annoying messages 😃 

I don't remember why I was using ctags instead of the default parser, I must have found that it worked better for the languages I'm primarily working in.

Makes perfect sense to see the message on first time database creation - so the user at least knows about it - but never again afterwards.

For me, these errors have never prevented me from doing anything I wanted to do with the plugin - like I've never encountered an identifier it couldn't "find definition" for. So the errors were minor overall and just an annoyance. In fact this plugin parses much better for JS than Notepad++'s included one that generates its built-in Function List.

**Comment by pnedev** [comment]
Great.
I have changed the behavior once again so now the warning/error message is shown only when creating the database for the first time (no matter the parser used) and it is suppressed on database update afterwards.
The new development binaries are these: [win32](https://ci.appveyor.com/api/buildjobs/hho6lmx2w32uuxn5/artifacts/NppGTags.x86.Release.v143.dll), [win64](https://ci.appveyor.com/api/buildjobs/pdavgss9ssct62b4/artifacts/NppGTags.x64.Release.v143.dll).
Could you please verify the change is working as expected?
Thanks :+1:

**Comment by marcelblum** [comment]
Yup, confirmed working as expected. Thanks again!

**Comment by pnedev** [comment]
Excellent, thanks!
