### ISSUE TITLE
DLL name returned has first letter cut off

### ISSUE THREAD

**Issue by vinsworldcom** [pnedev/nppgtags#43]
The call:

https://github.com/pnedev/nppgtags/blob/ef758569c5eb92e34cc3beb2df3b14e4057f69de/src/ResultWin.cpp#L506

sets the module name that gets written to Notepad++ 'config.xml' file.  However, the call goes to:

https://github.com/pnedev/nppgtags/blob/ef758569c5eb92e34cc3beb2df3b14e4057f69de/src/Common.cpp#L771-L783

where line 778 is wrong - it adds one back to the index of the array (0-based) but you're starting from a `Len()` (1-based).  This results in the following line in Notepad++ 'config.xml' file:

```XML
            <PluginDlg pluginName="ppGTags.dll" id="0" curr="3" prev="-1" isVisible="no" />
```

Missing the leading `N`. 

Cheers.

**Comment by pnedev** [comment]
Good catch, thanks for fixing this :+1: 

BR
