### ISSUE TITLE
Results dockable panel has no icon

### ISSUE THREAD

**Issue by vinsworldcom** [pnedev/nppgtags#45]
The results panel does not have an icon:

![image](https://github.com/pnedev/nppgtags/assets/9657169/e8a99a92-de01-4370-9f37-6ec9d010278a)

This can be easily remedied and use the Gnu GTags image from the website:

https://www.gnu.org/software/global/

Cheers.

**Comment by pnedev** [comment]
Cool, thanks for adding this,
BR
