### ISSUE TITLE
Incorrect escape sequence in regular expression

### ISSUE THREAD

**Issue by sgmne** [pnedev/nppgtags#47]
https://github.com/pnedev/nppgtags/blob/4a2a7df9d97572ee12bb3bd1a16651da27ab6754/bin/share/gtags/script/pygments_parser.py#L92
https://github.com/pnedev/nppgtags/blob/4a2a7df9d97572ee12bb3bd1a16651da27ab6754/bin/share/gtags/script/pygments_parser.py#L161

The strings having regular expression '\s' are missing the r string type for regular expression backslash (ore escaping the backslash)

**Comment by pnedev** [comment]
I don't understand well the regular expressions syntax and _pygments_parser.py_ is actually taken from external project.
I only made the plugin DLL as a frontend to the external binaries. Please feel free to make the changes necessary and create a PR.
Thank you.

**Comment by sgmne** [comment]
Invalid escape sequences in normal strings, even if valid regular expressions, have been deprecated in Python and will eventually be treated as errors. For that reason the pygments_parser.py won't work anymore in some setups. A simple correction is to change the affected strings to r-strings. The strings to be corrected are the ones having \s shown above. To convert them to r-strings, precede the string with r, like `r'\s'`  in the first one and `r'\s+(.*)$'` in the second instance.

**Comment by pnedev** [comment]
@sgmne ,
OK, I will fix this some time soon.
Thank you for the heads-up 👍

**Comment by pnedev** [comment]
Fix is done, it will be in the next plugin release,
Thanks again :+1:
