### ISSUE TITLE
Additional infos on readme

### ISSUE THREAD

**Issue by chcg** [pnedev/nppgtags#48]
Doesn't it make sense to add the link to the win32 libs (http://adoxa.altervista.org/global/) directly to the readme. I was not able to find that link on the GNU page.
Current version is 6.6.9. How is your strategy on updating these? Might be also of interest to add the currently used version to the readme if someone is missing a new feature/bugfix.

**Comment by pnedev** [comment]
Thanks for the heads-up and the suggestions @chcg ,
I will consider adding some info in the About dialog and in the README :+1: 

> Current version is 6.6.9. How is your strategy on updating these?

Currently I am not planning to be porting new GTags releases to Win32 myself so I will stick with GTags v6.6.9 until there are no other Window ports.

**Comment by chcg** [comment]
About the version I didn't look deep enough into the bin folder and just saw the last commit add the level above:

> [Update Universal CTags to v6.1.0](https://github.com/pnedev/nppgtags/commit/4a2a7df9d97572ee12bb3bd1a16651da27ab6754)

For GTags you are already using the latest available version. So everything ok from that side I would say.

**Comment by pnedev** [comment]
README and plugin's About info are updated, thanks
