### ISSUE TITLE
could Dialog "search in Source files" be modeless

### ISSUE THREAD

**Issue by besonzore** [pnedev/nppgtags#50]
could Dialog "search in Source files" be modeless
It seems more convinient to use the modeless dialog "find and replace" 
now in npptags, after confirming the search, the dialog close

**Comment by pnedev** [comment]
@besonzore ,
I have added an option to make the Search box persistent.
It will be available in the next version but meanwhile you can get the perfectly usable dev version:
[x64](https://ci.appveyor.com/api/buildjobs/ec5ltiu9mqdbuuwa/artifacts/NppGTags.x64.Release.v143.dll) / [x86](https://ci.appveyor.com/api/buildjobs/hli887t7g0n0wls6/artifacts/NppGTags.x86.Release.v143.dll)

**Comment by besonzore** [comment]
have tried the lastest version and found it in "settings ..." dialog
It's a great plugin for analyzing c code
the new feature of autocompletion is awesome too 
@pnedev
