### ISSUE TITLE
Results windows auto-expand option

### ISSUE THREAD

**Issue by cmeriaux** [pnedev/nppgtags#8]
Add an option that enable or disable auto expansion of results windows.

For "find reference" function, the results is supposed to be short. It could be nice that the result is directly visible

Cheers

**Comment by pnedev** [comment]
> For "find reference" function, the results is supposed to be short.

Depends on the code base. It might be quite long in fact. For _Find Definition_ I agree.

I think it is quite useful to be able to see directly the files that contain the results first (so the results are initially folded).
It is no big deal to press together `Alt` and `+` keys to unfold all results or to left-click with the mouse in the results first line margin (just above the first '+' unfolding sign) which does the same.

BR

**Comment by cmeriaux** [comment]
Thanks for the shortcut. I didn't know it exists. Is there others useful shortcuts ? I didn't found any of them in the help/config of the plugin
Cheers

**Comment by pnedev** [comment]
All of them are in the _README.md_ (unless I have missed something but I'm quite certain I haven't) - it is fully displayed at https://github.com/pnedev/nppgtags - just scroll down to the end.

BR
